project_name: kubeaudit
release:
  github:
    owner: Shopify
    name: kubeaudit
brew:
  github:
    owner: shopify
    name: homebrew-shopify
  install: bin.install "kubeaudit"
  homepage: "https://github.com/shopify/kubeaudit"
  description: "kubeaudit audits Kubernetes clusters for common security controls"
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: kubeaudit
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
